import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "primary-fixed": "#dae2fd",
        "surface-container-low": "#eff4ff",
        "on-tertiary": "#ffffff",
        "on-tertiary-fixed": "#23005c",
        "on-surface-variant": "#45464d",
        "on-surface": "#0b1c30",
        "secondary": "#0058be",
        "on-secondary-container": "#fefcff",
        "error-container": "#ffdad6",
        "primary": "#000000",
        "surface-bright": "#f8f9ff",
        "secondary-container": "#2170e4",
        "on-primary": "#ffffff",
        "surface": "#f8f9ff",
        "on-background": "#0b1c30",
        "tertiary-fixed-dim": "#d0bcff",
        "inverse-on-surface": "#eaf1ff",
        "outline-variant": "#c6c6cd",
        "on-secondary-fixed-variant": "#004395",
        "on-error-container": "#93000a",
        "on-tertiary-container": "#9466ff",
        "on-primary-fixed": "#131b2e",
        "inverse-primary": "#bec6e0",
        "on-primary-container": "#7c839b",
        "on-error": "#ffffff",
        "background": "#f8f9ff",
        "tertiary": "#000000",
        "outline": "#76777d",
        "tertiary-container": "#23005c",
        "surface-container-highest": "#d3e4fe",
        "inverse-surface": "#213145",
        "tertiary-fixed": "#e9ddff",
        "surface-container": "#e5eeff",
        "secondary-fixed": "#d8e2ff",
        "surface-dim": "#cbdbf5",
        "primary-fixed-dim": "#bec6e0",
        "on-primary-fixed-variant": "#3f465c",
        "on-secondary-fixed": "#001a42",
        "surface-container-high": "#dce9ff",
        "primary-container": "#131b2e",
        "on-tertiary-fixed-variant": "#5516be",
        "surface-variant": "#d3e4fe",
        "surface-tint": "#565e74",
        "error": "#ba1a1a",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#adc6ff"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "sm": "8px",
        "xs": "4px",
        "container-max": "1440px",
        "xl": "32px",
        "lg": "24px",
        "md": "16px",
        "margin-mobile": "16px",
        "2xl": "48px",
        "base": "4px",
        "3xl": "64px",
        "gutter": "24px"
      },
      "fontFamily": {
        "label-md": ["Geist", "sans-serif"],
        "body-sm": ["Geist", "sans-serif"],
        "headline-md": ["Geist", "sans-serif"],
        "headline-lg": ["Geist", "sans-serif"],
        "display-lg": ["Geist", "sans-serif"],
        "mono-data": ["Geist Mono", "monospace"],
        "headline-lg-mobile": ["Geist", "sans-serif"],
        "body-lg": ["Geist", "sans-serif"],
        "body-md": ["Geist", "sans-serif"]
      },
      "fontSize": {
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "mono-data": ["14px", { "lineHeight": "20px", "fontWeight": "500" }],
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "400" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
};
export default config;
